#  Name of workflow
name: Production workflow

# When workflow is triggered
on:
  push:
    branches:
      - master

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Create .env file
      - name: Create .env file
        run: |
          touch .env
          echo VITE_ENV=${{ secrets.VITE_ENV }} >> .env
          echo VITE_BASE_API_URL=${{ secrets.VITE_BASE_API_URL }} >> .env
          echo VITE_APP_PUBLIC_POSTHOG_KEY=${{ secrets.VITE_APP_PUBLIC_POSTHOG_KEY }} >> .env
          echo VITE_APP_PUBLIC_POSTHOG_HOST=${{ secrets.VITE_APP_PUBLIC_POSTHOG_HOST }} >> .env
          echo VITE_IS_TOGGLE_FEATURE=${{ secrets.VITE_IS_TOGGLE_FEATURE }} >> .env
          echo VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }} >> .env
          cat .env
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
